from node:latest

# TODO: create a working directory
# TODO: copy app.js in the workdir directory
# TODO: set an environment variable called MSG with a welcome message

# NodeJS framework for Web applications
run npm install express
# Launch application (see app.js for more details)
cmd node app.js
