local:
	cd ./src/back-end/config && ./create_back-end_local.sh

local-clean:
	cd ./src/back-end/config && ./clean_back-end_local.sh

azure:
	cd ./src/back-end/config && ./create_back-end_azure.sh

azure-clean:
	cd ./src/back-end/config && ./clean_back-end_azure.sh