local:
	cd ./src/back-end/config && ./create_back-end_local.sh

local-clean:
	cd ./src/back-end/config && ./clean_back-end_local.sh

local_VMs:
	cd ./src/back-end/config && ./create_back-end_local_VMs.sh && ./blob_config.sh

local_VMs-clean:
	cd ./src/back-end/config && ./clean_back-end_local_VMs.sh

azure:
	cd ./src/back-end/config && ./create_back-end_azure.sh

azure-clean:
	cd ./src/back-end/config && ./clean_back-end_azure.sh